package: slice_columns
version: dev-0.0.1
author: Andreas Lenhardt
supportpage: https://github.com/AndiLeni/statistics


requires:
  redaxo: '^5.11'
  packages:
  php:
    version: '>=7.1'


installer_ignore:
    - .git